#!/usr/bin/env python3
"""Fetch the boardroom theme's display font pair (Be Vietnam Pro + Fraunces,
both OFL) into assets/themes/boardroom/fonts/ for pixel-exact, fully
self-contained typography — including correct Vietnamese diacritics,
which is why these two were picked over the theme's original Fira Sans /
Times New Roman system-font stack (neither is Vietnamese-native; Be
Vietnam Pro was designed for it, verified by rendering real Vietnamese
text through both before switching, see references/themes.md).

build_book.py auto-includes assets/themes/<theme>/fonts.css whenever it
exists next to that theme's pdf.css/epub.css — no --extra-css flag
needed once this has been run. Without it, boardroom's pdf.css/epub.css
still fall back to the old system-font stack (Helvetica Neue/Arial,
Times New Roman/Georgia), so a host that can't reach Google Fonts still
gets a working, just less pixel-exact, build.

Fetched at 400/700 (the only two weights boardroom's CSS actually uses,
see pdf.css) and, for Fraunces specifically, pinned to its largest
optical-size axis instance (opsz=144) since it's used only for the
cover title/subtitle display type, not body text.
"""
import urllib.request
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
FONTS_DIR = SKILL_DIR / "assets" / "themes" / "boardroom" / "fonts"
FONTS_CSS = SKILL_DIR / "assets" / "themes" / "boardroom" / "fonts.css"

# Resolved once via https://fonts.googleapis.com/css2?family=...&display=swap
# (a plain "Mozilla/5.0" UA is enough to get .ttf back instead of .woff2 —
# no need to spoof an old-browser UA string). Re-resolve if these 404.
FILES = {
    "BeVietnamPro-Regular.ttf": "https://fonts.gstatic.com/s/bevietnampro/v12/QdVPSTAyLFyeg_IDWvOJmVES_Eww.ttf",
    "BeVietnamPro-Bold.ttf": "https://fonts.gstatic.com/s/bevietnampro/v12/QdVMSTAyLFyeg_IDWvOJmVES_HSMIF8y.ttf",
    "Fraunces-Regular.ttf": "https://fonts.gstatic.com/s/fraunces/v38/6NUh8FyLNQOQZAnv9bYEvDiIdE9Ea92uemAk_WBq8U_9v0c2Wa0K7iN7hzFUPJH58njr1a03gg7S2nfgRYIctxujDg.ttf",
    "Fraunces-Bold.ttf": "https://fonts.gstatic.com/s/fraunces/v38/6NUh8FyLNQOQZAnv9bYEvDiIdE9Ea92uemAk_WBq8U_9v0c2Wa0K7iN7hzFUPJH58njr1a03gg7S2nfgRYIcUByjDg.ttf",
}

CSS = """/* Generated by scripts/fetch_fonts.py — embeds Be Vietnam Pro
   (SIL OFL 1.1) and Fraunces at opsz=144 (SIL OFL 1.1). Auto-included
   by build_book.py whenever this file exists; see the script docstring
   for why these two fonts and why only 400/700. */
@font-face { font-family:"Be Vietnam Pro"; font-weight:400; src:url("fonts/BeVietnamPro-Regular.ttf"); }
@font-face { font-family:"Be Vietnam Pro"; font-weight:700; src:url("fonts/BeVietnamPro-Bold.ttf"); }
@font-face { font-family:"Fraunces"; font-weight:400; src:url("fonts/Fraunces-Regular.ttf"); }
@font-face { font-family:"Fraunces"; font-weight:700; src:url("fonts/Fraunces-Bold.ttf"); }
"""


def main():
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    for filename, url in FILES.items():
        dest = FONTS_DIR / filename
        if dest.exists():
            print(f"skip (already present): {filename}")
            continue
        print(f"fetching {filename} ...")
        urllib.request.urlretrieve(url, dest)
    FONTS_CSS.write_text(CSS)
    print(f"Wrote {FONTS_CSS}")
    print("build_book.py --theme boardroom now uses these automatically.")


if __name__ == "__main__":
    main()
